### ISSUE TITLE
Docker magic.

### ISSUE THREAD

**Issue by Fillll** [Fillll/reddit2telegram#13]
It will be much more easy to operate with it using docker.

There should be two containers:
1. Mongo (just for storing already sended submissions).
2. Sender itself (always alive with cron inside).

**Comment by luckydonald** [comment]
Cron is probably a bad choice, because you have to start the bash subsystem or something.
Normally you just start a single process. Like a 
```python
while true:
  # do stuff
  sleep(60)
```

You can add `restart: "unless-stopped"` to the [`docker-compose.yml`](https://github.com/Fillll/reddit2telegram/blob/28ca60b6512ea1cd62dcded21f924a25e700c723/docker-compose.yml#L4), so the container will restart on crashes, until you turn them off.
(`restart: "always"` would restart shut down containers on host reboot, e.g. a power failure, even if they were shut down manually before)

**Comment by luckydonald** [comment]
Right now you can probably put `docker-compose up -d` (you probably need to `cd` to the path or something) in your cron job of the **host** system (not inside the container)

**Comment by luckydonald** [comment]
Actually there are images using cron.
https://github.com/Annixa/docker-pg_dump/

**Comment by Fillll** [comment]
Oh.

**Comment by luckydonald** [comment]
Oh.
