### ISSUE TITLE
Send albums as actual albums instead of one image per message

### ISSUE THREAD

**Issue by nyuszika7h** [Fillll/reddit2telegram#83]
Telegram added support for albums of up to 10 items a while ago, this would be better than sending each message from an album as a separate message. Here's the relevant bot API documentation: https://core.telegram.org/bots/api#sendmediagroup

**Comment by RememberTheAir** [comment]
This would either require telepot to support [InputMediaPhoto/Video](https://core.telegram.org/bots/api#inputmediaphoto) (unlikely, the library seems to be dead) or a telepot fork with at least support to InputMedia objects (which sounds like an unreasonable effort).

I think we should consider to move to a more up-to-date and supported library, like python-telegram-bot

**Comment by Fillll** [comment]
Sounds like good idea!I you start migrating it to python-telegram-bot that will be much appreciated. 26.02.2019, 13:12, "RememberTheAir" <notifications@github.com>:This would either require telepot to support InputMediaPhoto/Video (unlikely, the library seems to be dead) or a telepot fork with at least support to InputMedia objects (which sounds like an unreasonable effort).I think we should consider to move to a more up-to-date and supported library, like python-telegram-bot—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.  -- Alexander Filatov

**Comment by RememberTheAir** [comment]
I can open a PR during the next week

**Comment by RememberTheAir** [comment]
I opened a separate issue (#96) about this

**Comment by Fillll** [comment]
Already done!
So now we have a gallery for Reddit galleries, send as albums in Telegram.
And Imgur albums, that named albums and send pic by pic.
